collectivework/urls.py
from django.conf.urls import static
from django.conf.urls import url, include
from django.contrib import admin
from postman import urls as postman_urls

from collectivework import settings
from collectivework.views import site_rules, help
from ticket import urls as ticket_urls
from  userprofile import urls as userprofile_urls

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^messages/', include(postman_urls, namespace='postman', app_name='postman')),
    url(r'^user/', include(userprofile_urls, namespace='userprofile', app_name='userprofile')),
    url(r'^site_rules/$', site_rules, name='site_rules'),
    url(r'^help/$', help, name='help'),
    url(r'^', include(ticket_urls, namespace="collectivework", app_name="ticket"), name="index"),
]

if settings.DEBUG is True:
    urlpatterns += static.static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ticket/urls.py
from django.conf.urls import url

from ticket.views import list_ticket, create_ticket, list_my_ticket, list_moderation_requests, show_ticket

urlpatterns = [
    url(r'^$', list_ticket, name='list_ticket'),
    url(r'^create/$', create_ticket, name='create_ticket'),
    url(r'^my/$', list_my_ticket, name='list_my_ticket'),
    url(r'^list_moderation_request/$', list_moderation_requests, name='list_moderation_requests'),
    url(r'^(?P<id>\w+)/$', show_ticket, name='show_ticket'),
]

ticket/models.py
import datetime

from django.contrib.auth.models import User
from django.db import models


class TicketTag(models.Model):
    name = models.CharField(max_length=20, verbose_name="Etiket")

    def __str__(self):
        return self.name


class Ticket(models.Model):
    title = models.CharField(max_length=100, verbose_name="Başlık")
    short_desc = models.CharField(max_length=300, verbose_name="Kısa açıklama")
    long_desc = models.CharField(max_length=1000, verbose_name="Uzun açıklama", blank=True, null=True)
    creation_date = models.DateField(verbose_name="Olusturulma tarihi", default=datetime.date.today)
    end_date = models.DateField(verbose_name="Geçerlilik süresi", default=datetime.date.today)
    request_in_user = models.ForeignKey(User, related_name="requestinguser", verbose_name="Talepte Bulunan Kulanıcı")
    accepted = models.BooleanField(default=False)
    rejected = models.BooleanField(default=False)
    completed = models.BooleanField(default=False)
    assigned_user = models.ForeignKey(User, related_name="assigned_user", verbose_name="Gönüllü", blank=True, null=True)
    tag = models.ManyToManyField(TicketTag, verbose_name="Etiket")
    progress = models.CharField(max_length=3, verbose_name="İşin tamamlanma oranı", blank=True, null=True)

    def __str__(self):
        return self.title

ticket/forms.py
from django.forms import ModelForm
from django.forms.widgets import TextInput, HiddenInput, Textarea, DateInput, SelectMultiple

from ticket.models import Ticket


class CreateTicketForm(ModelForm):
    class Meta:
        model = Ticket
        exclude = ['creation_date', 'progress', 'assigned_user', 'accepted', 'rejected', 'completed']
        widgets = {
            'title': TextInput(attrs={'class': 'form-control'}),
            'short_desc': TextInput(attrs={'class': 'form-control'}),
            'long_desc': Textarea(attrs={'class': 'form-control'}),
            'end_date': DateInput(attrs={'id': 'datepicker', 'class': 'form-control pull-right'}),
            'tag': SelectMultiple(attrs={'class': 'form-control'}),
            'request_in_user': HiddenInput(),
            'accepted': HiddenInput(),
            'rejected': HiddenInput(),
            'completed': HiddenInput(),
        }

    def __init__(self, *args, **kwargs):
        super(CreateTicketForm, self).__init__(*args, **kwargs)
        for field in self.fields:
            self.fields[field].required = True
        self.fields['request_in_user'].required = False

ticket/views.py
from django.contrib.admin.views.decorators import staff_member_required
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.urls import reverse

from collectivework import settings
from ticket.forms import CreateTicketForm
from ticket.models import Ticket


def list_ticket(request):
    tickets = []
    if request.user:
        if request.user.is_staff:
            tickets = Ticket.objects.all().order_by('-creation_date')
        elif request.user.is_authenticated():
            tickets = Ticket.objects.filter(accepted=True).order_by('-creation_date')
        else:
            tickets = Ticket.objects.filter(accepted=True, completed=False, assigned_user=None).order_by(
                '-creation_date')

    return render(request, 'list_ticket.html', {'tickets': tickets})


@login_required(login_url=settings.LOGIN_URL)
def create_ticket(request):
    if request.POST:
        form = CreateTicketForm(request.POST)
        if form.is_valid():
            ticket = form.save(commit=False)
            ticket.request_in_user = request.user
            ticket.save()
            return HttpResponseRedirect('/ticket/')
    else:
        form = CreateTicketForm()
    return render(request, 'detail_ticket.html', {'form': form, 'title': "Yeni İstek Oluştur", 'creation': True})


@login_required(login_url=settings.LOGIN_URL)
def show_ticket(request, id):
    ticket = get_object_or_404(Ticket, pk=id)
    form = CreateTicketForm(instance=ticket)
    return render(request, 'detail_ticket.html',
                  {'form': form, 'title': "İstek Numarası: %s" % ticket.pk, 'creation': False})


@login_required(login_url=settings.LOGIN_URL)
def list_my_ticket(request):
    tickets = Ticket.objects.filter(assigned_user=request.user).order_by('-creation_date')
    return render(request, 'list_ticket.html', {'tickets': tickets})


@staff_member_required
def list_moderation_requests(request):
    tickets = Ticket.objects.filter(accepted=False, rejected=False, completed=False).order_by('-creation_date')
    return render(request, 'list_ticket.html', {'tickets': tickets})

ticket/templates/detail_ticket.html
{% extends 'base.html' %}

{% block content %}
    <div style="padding-top: 30px; padding-left: 30px;">

        <div class="col-lg-5">

            <div class="row">
                <div class="box-header with-border">
                    <h3 class="box-title">{{ title }}</h3>
                </div>
                <form role="form" method="POST">
                    {% csrf_token %}
                    <div class="box-body">
                        {% for field in form.visible_fields %}
                            {% if field.id == 'datepicker' %}
                                <div class="form-group">
                                    <label>{{ field.label }}</label>
                                    <div class="input-group date">
                                        <div class="input-group-addon">
                                            <i class="fa fa-calendar"></i>
                                        </div>
                                        {{ field }}
                                    </div>
                                </div>

                            {% else %}
                                <div class="form-group">
                                    <label>{{ field.label }}</label>
                                    {{ field }}
                                    {% if field.errors %}
                                        <div class="row">
                                            <div class="col-md-6 col-md-offset-2">
                                                <span class="label label-danger">{{ field.label }}: {{ field.errors|striptags }}</span>
                                            </div>
                                        </div>
                                    {% endif %}
                                </div>
                            {% endif %}
                        {% endfor %}
                    </div>
                    <div class="box-footer">
                        {% if creation %}
                        <button type="submit" class="btn btn-primary">Gönder</button>
                        {% endif %}
                    </div>
                </form>

            </div>
        </div>
    </div>
{% endblock %}

ticket/templates/list_ticket.html
{% extends 'base.html' %}

{% block content %}
    <section class="content-header">
        <h1>
            Gönüllü olarak yapacağımız işlerimiz var..
        </h1>
    </section>
    <div style="padding-top: 30px">
    </div>

    {% if not user.is_authenticated %}
        <div class="callout callout-info">
            <p>İş üstlenmek veya yardım istemek için öncelikle hesabınız ile giriş yapın!</p>
        </div>
    {% endif %}

    <ul class="timeline col-lg-8 col-md-8">
        {% for ticket in tickets %}
            <li class="time-label">
                {% ifchanged ticket.creation_date %}
                    <span class="bg-red">{{ ticket.creation_date }}</span>
                {% endifchanged %}
            </li>
            <li>
                <i class="fa fa-ticket bg-blue"></i>
                <div class="timeline-item">
                    <span class="time">İş Numarası: {{ ticket.pk }}</span>

                    <h3 class="timeline-header"><a href="{% url 'ticket:show_ticket' ticket.pk %}">{{ ticket.title }}</a></h3>

                    <div class="timeline-body">
                        {{ ticket.short_desc }}
                    </div>

                    <div class="timeline-footer">
                        <div class="progress xs">
                            <div class="progress-bar progress-bar-green" style="width: {{ ticket.progress }}%;"></div>
                        </div>
                        {% for tag in ticket.tag.all %}
                            <small class="label label-warning">{{ tag.name }}</small>
                        {% endfor %}
                    </div>

                </div>
            </li>

        {% empty %}

            <div class="alert alert-danger">
                <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                <h4><i class="icon fa fa-warning"></i> Uyarı!</h4>
                Üzgünüz, burada henüz iş yok!
            </div>

        {% endfor %}

    </ul>

{% endblock %}