collectivework/urls.py
from django.conf.urls import static
from django.conf.urls import url, include
from django.contrib import admin
from postman import urls as postman_urls

from collectivework import settings
from collectivework.views import site_rules, help
from ticket import urls as ticket_urls
from  userprofile import urls as userprofile_urls

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^messages/', include(postman_urls, namespace='postman', app_name='postman')),
    url(r'^user/', include(userprofile_urls, namespace='userprofile', app_name='userprofile')),
    url(r'^site_rules/$', site_rules, name='site_rules'),
    url(r'^help/$', help, name='help'),
    url(r'^', include(ticket_urls, namespace="collectivework", app_name="ticket"), name="index"),
]

if settings.DEBUG is True:
    urlpatterns += static.static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ticket/urls.py
from django.conf.urls import url

from ticket.views import list_ticket, create_ticket, list_my_ticket, list_moderation_requests, show_ticket

urlpatterns = [
    url(r'^$', list_ticket, name='list_ticket'),
    url(r'^create/$', create_ticket, name='create_ticket'),
    url(r'^my/$', list_my_ticket, name='list_my_ticket'),
    url(r'^list_moderation_request/$', list_moderation_requests, name='list_moderation_requests'),
    url(r'^(?P<id>\w+)/$', show_ticket, name='show_ticket'),
]

userprofile/urls.py
from django.conf.urls import url


from ticket.views import list_ticket, create_ticket, list_my_ticket, list_moderation_requests, show_ticket
from userprofile.views import login, logout, signup, update

urlpatterns = [
    url(r'^login/$', login, name="login"),
    url(r'^signup/$', signup, name="signup"),
    url(r'^update/$', update, name="update"),
    url(r'^logout/$', logout, name="logout"),
]

userprofile/models.py
import os

from django.contrib.auth.models import User
from django.db import models

from collectivework import settings


def get_image_path(instance, filename):
    return os.path.join(settings.MEDIA_URL, 'images', str(instance.user.id), filename)


class UserProfile(models.Model):
    user = models.OneToOneField(User)
    profile_photo = models.ImageField(upload_to=get_image_path, blank=True, null=True)

    def __unicode__(self):
        return self.user.username

    def get_image_relative_path(self):
        return os.path.join('static', 'images', str(self.user.id), self.profile_photo.name)

userprofile/forms.py
from django import forms
from django.contrib.auth.models import User
from django.forms import ModelForm

from userprofile.models import UserProfile


class UserForm(ModelForm):
    class Meta:
        model = User
        fields = ['email', 'username', 'password']
        labels = {
            'email': "E-posta",
            'username': "Kullanıcı Adı",
            'password': "Parola"
        }
        widgets = {
            'email': forms.TextInput(attrs={'placeholder': 'E-posta', 'class': 'form-control'}),
            'username': forms.TextInput(attrs={'placeholder': 'Kullanıcı Adı', 'class': 'form-control'}),
            'password': forms.PasswordInput(attrs={'placeholder': 'Parola', 'class': 'form-control'})
        }


class UserUpdateForm(ModelForm):
    class Meta:
        model = User
        fields = ['email', 'username']
        labels = {
            'email': "E-posta",
            'username': "Kullanıcı Adı"
        }
        widgets = {
            'email': forms.TextInput(attrs={'placeholder': 'E-posta', 'class': 'form-control'}),
            'username': forms.TextInput(attrs={'placeholder': 'Kullanıcı Adı', 'class': 'form-control'})
        }


class UserProfileForm(ModelForm):
    class Meta:
        model = UserProfile
        fields = ['profile_photo']
        labels = {
            'profile_photo': "Profil Fotoğrafı"
        }

userprofile/views.py
from django.contrib.auth import authenticate
from django.contrib.auth import logout as user_logout, login as user_login
from django.contrib.auth.decorators import login_required
from django.core.exceptions import ObjectDoesNotExist
from django.http import HttpResponseRedirect
from django.shortcuts import render, redirect
from django.urls import reverse
from django.views.decorators.csrf import csrf_exempt

from collectivework import settings
from userprofile.forms import UserProfileForm, UserForm, UserUpdateForm


@csrf_exempt
def login(request):
    data = {}
    note = None
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(username=username, password=password)
        if user is not None:
            user_login(request, user)
            return HttpResponseRedirect(request.GET['next'])
        note = "Giriş Başarısız"
    data['note'] = note
    return render(request, "login.html", data)

def signup(request):
    if request.POST:
        userprofile_form = UserProfileForm(request.POST, request.FILES, prefix='userprofile_form')
        user_form = UserForm(request.POST, request.FILES, prefix='user_form')
        if all([userprofile_form.is_valid(), user_form.is_valid()]):
            user = user_form.save()
            profile = userprofile_form.save(commit=False)
            profile.user = user
            profile.save()
            user_login(request, user)
            return HttpResponseRedirect(reverse("userprofile:login"))
    else:
        userprofile_form = UserProfileForm(prefix='userprofile_form')
        user_form = UserForm(prefix='user_form')
    return render(request, "signup.html", {
        'userprofile_form': userprofile_form,
        'user_form': user_form
    })

@login_required(login_url=settings.LOGIN_URL)
def update(request):
    data = {}
    if request.POST:
        try:
            userprofile_form = UserProfileForm(request.POST, request.FILES, prefix='userprofile_form', instance=request.user.userprofile)
        except ObjectDoesNotExist:
            userprofile_form = UserProfileForm(request.POST, request.FILES, prefix='userprofile_form')
        user_form = UserUpdateForm(request.POST, request.FILES, prefix='user_form', instance=request.user)
        if all([userprofile_form.is_valid(), user_form.is_valid()]):
            user = user_form.save()
            profile = userprofile_form.save(commit=False)
            profile.user = user
            profile.save()
            return redirect(reverse("userprofile:update"))
    else:
        user_form = UserUpdateForm(instance=request.user, prefix='user_form')
        try:
            userprofile_form = UserProfileForm(prefix='userprofile_form', instance=request.user.userprofile)
        except ObjectDoesNotExist:
            userprofile_form = UserProfileForm(prefix='userprofile_form')
    data['userprofile_form'] = userprofile_form
    data['user_form'] = user_form
    return render(request, "update.html", data)

def logout(request):
    user_logout(request)
    return HttpResponseRedirect("/")

userprofile/templates/login.html
{% extends 'base.html' %}

{% block content %}

    <section class="content-header">
        <h1>
            Kullanıcı Girişi
        </h1>
    </section>

    <div class="login-box">

        <div class="login-box-body">
            <form method="post">
                <div class="form-group has-feedback">
                    <input type="text" name="username" class="form-control" placeholder="Kullanıcı Adı">
                </div>
                <div class="form-group has-feedback">
                    <input type="password" name="password" class="form-control" placeholder="Parola">
                </div>

                <div class="form-group pull-right">
                    <button type="submit" class="btn btn-primary">Giriş</button>
                </div>
            </form>

            <a href="{% url "userprofile:signup" %}" class="text-center">Yeni Kullanıcı</a>

        </div>
    </div>
{% endblock %}

userprofile/templates/signup.html
{% extends "base.html" %}

{% block content %}

    <section class="content-header">
        <h1>
            Yeni Kullanıcı
        </h1>
    </section>
    <div class="login-box">
        <div class="login-box-body">
            <form method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                {% if user_form %}
                    {% for field in user_form.visible_fields %}
                        <div class="form-group">
                            <div class="row">

                                <b>{{ field.label }}</b>
                                {{ field }}
                            </div>
                            {% if field.errors %}
                                <div class="row">
									<span class="label label-danger">
										{{ field.label }}: {{ field.errors|striptags }}
									</span>
                                </div>
                            {% endif %}
                        </div>
                    {% endfor %}
                {% endif %}
                {% if userprofile_form %}
                    {% for field in userprofile_form.visible_fields %}
                        <div class="form-group">
                            <div class="row">
                                <b>{{ field.label }}</b>
                                {{ field }}
                            </div>
                            {% if field.errors %}
                                <div class="row">
									<span class="label label-danger">
										{{ field.label }}: {{ field.errors|striptags }}
									</span>
                                </div>
                            {% endif %}
                        </div>
                    {% endfor %}
                {% endif %}
                <div class="row">
                    <input type="submit" class="btn btn-primary pull-right" value="Kaydet"/>
                </div>
            </form>
        </div>
    </div>
{% endblock %}

userprofile/templates/update.html
{% extends "base.html" %}

{% block content %}

    <section class="content-header">
        <h1>
            Profil Güncelleme
        </h1>
    </section>
    <div class="login-box">
        <div class="login-box-body">
            <form method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                {% if user_form %}
                    {% for field in user_form.visible_fields %}
                        <div class="form-group">
                            <div class="row">

                                <b>{{ field.label }}</b>
                                {{ field }}
                            </div>
                            {% if field.errors %}
                                <div class="row">
									<span class="label label-danger">
										{{ field.label }}: {{ field.errors|striptags }}
									</span>
                                </div>
                            {% endif %}
                        </div>
                    {% endfor %}
                {% endif %}
                {% if userprofile_form %}
                    {% for field in userprofile_form.visible_fields %}
                        <div class="form-group">
                            <div class="row">
                                <b>{{ field.label }}</b>
                                {{ field }}
                            </div>
                            {% if field.errors %}
                                <div class="row">
									<span class="label label-danger">
										{{ field.label }}: {{ field.errors|striptags }}
									</span>
                                </div>
                            {% endif %}
                        </div>
                    {% endfor %}
                {% endif %}
                <div class="row">
                    <input type="submit" class="btn btn-primary pull-right" value="Kaydet"/>
                </div>
            </form>
        </div>
    </div>
{% endblock %}