collectivework/urls.py
from django.conf.urls import static
from django.conf.urls import url, include
from django.contrib import admin
from postman import urls as postman_urls

from collectivework import settings
from collectivework.views import site_rules, help
from ticket import urls as ticket_urls
from  userprofile import urls as userprofile_urls

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^messages/', include(postman_urls, namespace='postman', app_name='postman')),
    url(r'^user/', include(userprofile_urls, namespace='userprofile', app_name='userprofile')),
    url(r'^site_rules/$', site_rules, name='site_rules'),
    url(r'^help/$', help, name='help'),
    url(r'^', include(ticket_urls, namespace="collectivework", app_name="ticket"), name="index"),
]

if settings.DEBUG is True:
    urlpatterns += static.static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ticket/urls.py
from django.conf.urls import url

from ticket.views import list_ticket, create_ticket, list_my_ticket, list_moderation_requests, show_ticket

urlpatterns = [
    url(r'^$', list_ticket, name='list_ticket'),
    url(r'^create/$', create_ticket, name='create_ticket'),
    url(r'^my/$', list_my_ticket, name='list_my_ticket'),
    url(r'^list_moderation_request/$', list_moderation_requests, name='list_moderation_requests'),
    url(r'^(?P<id>\w+)/$', show_ticket, name='show_ticket'),
]

userprofile/urls.py
from django.conf.urls import url


from ticket.views import list_ticket, create_ticket, list_my_ticket, list_moderation_requests, show_ticket
from userprofile.views import login, logout, signup, update

urlpatterns = [
    url(r'^login/$', login, name="login"),
    url(r'^signup/$', signup, name="signup"),
    url(r'^update/$', update, name="update"),
    url(r'^logout/$', logout, name="logout"),
]

templates/about.html
{% extends 'base.html' %}

{% block content %}

{% endblock%}

templates/base.html
{% load staticfiles %}
<head>
    {% include 'static_base.html' %}
</head>

<body class="skin-blue fixed">
<header class="header">
    <a href="/" class="logo">Collectivework</a>
    <nav class="navbar navbar-static-top" role="navigation">
    </nav>
</header>

<div class="wrapper row-offcanvas row-offcanvas-left">
    <aside class="left-side sidebar-offcanvas">
        <section class="sidebar">
            <div class="user-panel">
                {% if user and not user.is_anonymous %}
                    <div class="user-panel">
                        {% if user.userprofile and user.userprofile.profile_photo %}
                            <div class="pull-left image">
                                <img src="/{{ user.userprofile.profile_photo.url }}" class="img-circle" alt="Fotograf">
                            </div>
                        {% endif     %}
                        <div class="pull-left info">
                            <p>{{ user.username }} </p>
                            <a href="{% url 'userprofile:logout' %}"><i class="fa fa-circle text-success"></i>Çıkış Yap</a>
                        </div>
                    </div>
                {% else %}
                    <div class="pull-left info">
                        <a href="{% url 'userprofile:login' %}?next={{ request.path }}"><i
                                class="fa fa-user text-success"></i>Kullanıcı Girişi</a>
                    </div>
                {% endif %}
            </div>

            <ul class="sidebar-menu">
                {% if user and not user.is_anonymous %}
                    <li class="active">
                        <a href="{% url 'userprofile:update' %}">
                            <i class="fa fa-edit"></i>
                            <span>Profil Güncelleme</span>
                        </a>
                    </li>
                    <li class="active">
                        <a href="#">
                            <i class="fa fa-envelope-o"></i>
                            <span>Mesajlar</span>
                            <i class="fa fa-angle-left pull-right"></i>
                        </a>
                        <ul class="active" style="list-style-type: none;">
                            <li class="active"><a href="{% url 'postman:inbox' %}"><i
                                    class="fa fa-inbox"></i><span> Gelen Kutusu</span></a></li>
                            <li class="active"><a href="{% url 'postman:sent' %}"><i
                                    class="fa fa-plane"></i><span> Gönderilenler</span></a></li>
                            <li class="active"><a href="{% url 'postman:write' %}"><i
                                    class="fa fa-pencil"></i><span> Olustur</span></a></li>
                            <li class="active"><a href="{% url 'postman:archive' %}"><i
                                    class="fa fa-floppy-o"></i><span> Arşiv</span></a></li>
                            <li class="active"><a href="{% url 'postman:trash' %}"><i class="fa fa-trash-o"></i><span> Çöp</span></a>
                            </li>
                        </ul>
                    </li>
                    <li class="active">
                        <a href="{% url 'ticket:create_ticket' %}">
                            <i class="fa fa-edit"></i>
                            <span>Yeni İş Oluştur</span>
                        </a>
                    </li>
                    <li class="active">
                        <a href="{% url 'ticket:list_my_ticket' %}">
                            <i class="fa fa-list-alt"></i>
                            <span>İşlerim</span>
                        </a>
                    </li>
                    {% if user.is_staff %}
                        <li class="active">
                            <a href="{% url 'ticket:list_moderation_requests' %}">
                                <i class="fa fa-tasks"></i>
                                <span>Moderasyondaki isler</span>
                            </a>
                        </li>
                    {% endif %}
                {% endif %}
                <li class="active">
                    <a href="{% url 'site_rules' %}">
                        <i class="fa fa-briefcase"></i>
                        <span>Kullanım Kuralları</span>
                    </a>
                </li>
                <li class="active">
                    <a href="{% url 'help' %}">
                        <i class="fa fa-info"></i>
                        <span>Yardım</span>
                    </a>
                </li>

            </ul>
        </section>
    </aside>
    <aside class="right-side">
        {% block content %}
        {% endblock %}
    </aside>
</div>


</body>

templates/help.html
{% extends 'base.html' %}

{% block content %}
    <section class="content-header">
        <h1>
            Yardım
        </h1>
    </section>
{% endblock%}

templates/site_rules.html
{% extends 'base.html' %}

{% block content %}
    <section class="content-header">
        <h1>
            Site Kuralları
        </h1>
    </section>

{% endblock%}

templates/siterules.html
{% extends 'base.html' %}

{% block content %}

{% endblock%}

templates/static_base.html
{% load staticfiles %}

{% block js %}
    <meta charset="UTF-8">
    <title>{{ pagetitle }}</title>
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    <!-- bootstrap 3.0.2 -->
    <link href='{% static "theme/adminlte/css/bootstrap.min.css" %}' rel="stylesheet"  type="text/css">
    <!-- font Awesome -->
    <link href='{% static "theme/adminlte/css/font-awesome.min.css"%}' rel="stylesheet" type="text/css">
    <!-- Ionicons -->
    <link href='{% static "theme/adminlte/css/ionicons.min.css"%}' rel="stylesheet" type="text/css">
    <!-- Morris chart -->
    <link href='{% static "theme/adminlte/css/morris/morris.css"%}' rel="stylesheet" type="text/css">
    <!-- jvectormap -->
    <link href='{% static "theme/adminlte/css/jvectormap/jquery-jvectormap-1.2.2.css" %}' rel="stylesheet" type="text/css">
    <!-- fullCalendar -->
    <link href='{% static "theme/adminlte/css/fullcalendar/fullcalendar.css" %}' rel="stylesheet" type="text/css">
    <!-- Daterange picker -->
    <link href='{% static "theme/adminlte/css/daterangepicker/daterangepicker-bs3.css" %}' rel="stylesheet" type="text/css">
    <!-- bootstrap wysihtml5 - text editor -->
    <link href='{% static "theme/adminlte/css/bootstrap-wysihtml5/bootstrap3-wysihtml5.min.css" %}' rel="stylesheet" type="text/css">
    <!-- Theme style -->
    <link href='{% static "theme/adminlte/css/AdminLTE.css" %}' rel="stylesheet" type="text/css">
    <link href='{% static "css/collectivework-main.css" %}' rel="stylesheet" type="text/css">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
    <![endif]-->

        
   	<script src="http://ajax.googleapis.com/ajax/libs/jquery/2.0.2/jquery.min.js"></script>
	<script src='{% static "theme/adminlte/js/jquery-ui-1.10.3.min.js" %}' type="text/javascript"></script>
	<script src='{% static "theme/adminlte/js/bootstrap.min.js" %}' type="text/javascript"></script>
	<script src="//cdnjs.cloudflare.com/ajax/libs/raphael/2.1.0/raphael-min.js"></script>
	<script src='{% static "theme/adminlte/js/plugins/morris/morris.min.js" %}' type="text/javascript"></script>
	<script src='{% static "theme/adminlte/js/plugins/sparkline/jquery.sparkline.min.js" %}' type="text/javascript"></script>
	<script src='{% static "theme/adminlte/js/plugins/jvectormap/jquery-jvectormap-1.2.2.min.js" %}' type="text/javascript"></script>
	<script src='{% static "theme/adminlte/js/plugins/jvectormap/jquery-jvectormap-world-mill-en.js" %}' type="text/javascript"></script>
	<script src='{% static "theme/adminlte/js/plugins/fullcalendar/fullcalendar.min.js" %}' type="text/javascript"></script>
	<script src='{% static "theme/adminlte/js/plugins/jqueryKnob/jquery.knob.js" %}' type="text/javascript"></script>
	<script src='{% static "theme/adminlte/js/plugins/daterangepicker/daterangepicker.js" %}' type="text/javascript"></script>
	<script src='{% static "theme/adminlte/js/plugins/bootstrap-wysihtml5/bootstrap3-wysihtml5.all.min.js" %}' type="text/javascript"></script>
	<script src='{% static "theme/adminlte/js/plugins/iCheck/icheck.min.js" %}' type="text/javascript"></script>

	<script src='{% static "js/collectivework-main.js" %}' type="text/javascript"></script>
	

{% endblock %}